language: python
cache:
  directories:
    - "$PIP_CACHE_DIR"
    - "$PIPENV_CACHE_DIR"
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
matrix:
  fast_finish: true
  include:
    - name: Conda on Windows
      os: windows
      language: shell
      env:
      - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
      - choco install python openssl.light
      install:
      - pip install pipenv
      - pipenv install -d
      - pip list
      - pipenv run pip list
before_script:
- |
  if [[ -n ${TRAVIS_TAG} ]]
  then
    echo $TRAVIS_TAG > src/VERSION
  fi
script:
- echo "Look ma no tests"
before_deploy:
- pipenv run pip install pyinstaller
- |
  curl -sL "https://api.github.com/repos/3ll3d00d/ezmote/releases/assets/12914946" -o ezmote.tar.gz -H 'Accept: application/octet-stream'
- mkdir ezmote
- tar xvfz ezmote.tar.gz -C ezmote
- rm ezmote.tar.gz
- pipenv run pyinstaller --clean --log-level=INFO -F cmdserver.spec
deploy:
  provider: releases
  api_key:
    secure: uD4bnS1EQTh7X848tsQkj6AJ4S3MFBt3sgUHNkuvgA+YYTIUfBZ2kBZQaP5W900MMon2PNQ3gHDYWH2V1nPeN8LFEKUZK0xBHJcxgX7TQfdGzG9+xrwAOmB2OTvtkXLC2Q8Lp6962C3X0nR4eyP7zeZYjzB7tnzgHYwbpqCfl9nbsqpiNYBg2Yy/Kp4nf0uhjc2aZ4ACKE5JVyypcklYzqP58uvFAvcli9tXGKS/D0kH1L8ol9Y1IbMxQpyGEnLxlET1lyygbpB2A+bN8NY9aKKXdQnfso53OZTuWqnQ4MlyagRkYUuhwiLSRjzKjGlZkj3RU+duX/GiLmyCUbXdN+pPdIRRUNB/YMygA33pP3waCeA3AbmQRMRu5U34UczMyQpiyiOBsWrlxGFLQdptfg7xgsqSqRTU7+Cuu/X/9tOQGg66IyVEnEP9a3TVkF8LPHXLcsTJCudHXL7Z9O51KPgEF6AQHan6CZq4LLTkWCPCQ4C6cM4wlZF/B4awywaN/dekTQRAclHwMxGAtGYs7j6fse38rw4J+ItXvwrVJMxiVrpTKsRFsVNjUF6dWOEeytGieM6cEy/UDgswHfjr8R2Mq25aIU2BXNzSBKn9Cf8dlc5O1UWCNfEBjd1V+UX2xujwabn1uEihfMy9tXF86kLPU62Agb3r1U2GpFHVRAI=
  file: dist/cmdserver.exe
  on:
    repo: 3ll3d00d/cmdserver
    tags: true
  skip_cleanup: true
  prerelease: true